#!/bin/bash


read -p 'url:' url
read -p "how many? (default is 500): " default_result_count

result=$(python /home/khashayar/dev/stuff/commanto/fetch.py $url $default_result_count)

echo "$result" | fzf