#!/bin/bash
## commanto! it does stuff with youtube comments
## this scriptreads the input and runs the
## python to start getting commands

default_result_count=100

if [[ $1 = "test" ]]; then
    url="https://www.youtube.com/watch?v=ZkNMZlkrzaU&ab_channel=Stephahahan"
    fetch_count=200
else
    read -p 'url:' url
    read -p "how many? (default is $default_result_count): " fetch_count
fi

if [[ -z $fetch_count ]]; then
    fetch_count=$default_result_count
fi

python /home/khashayar/dev/stuff/commanto/fetch.py $url $fetch_count